name: Ping Replit

on:
  schedule:
    - cron: '*/10 * * * *'  # toutes les 10 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Envoyer un ping à Replit
        run: curl -s https://replit.com/@soidikminaxio/mon-bot-discord


